#!/usr/bin/env php
<?php
require_once __DIR__.'/../sample/bootstrap.php';
// Если вы не используете composer, то можно использовать include
// require_once __DIR__.'/../lib/GetCourse/autoload.php';
$user = new \GetCourse\User();
// Замените на ваш аккаунт
$user::setAccountName('k1.getcourse.ru');
// Замените токен на сгенерированный вашим аккаунтом (http://k1.getcourse.ru/saas/account/api)
$user::setAccessToken('b3In8tcEeLRZ0RuIJsthZp6PDknqVEiDs0ib0AveVYVvfLpNsHC02f0sh0tG6xzO93AQFcocXwKMElxchlDVU8aljQ7Hc8zKVR78GGb7S0JplVuSZisr7IVxLYRJUupq');
try {
	$result = $user
		->setEmail('vasiliy.pupkin@getcourse.ru')
		->setFirstName('Василий')
		->setLastName('Пупкин')
		->setUserAddField('Почтовый адрес', 'New Васюки')
		->setGroup('шахматисты')
		->setGroup('дилетанты')
		->setOverwrite()
		->setSessionReferer('http://getcourse.ru')
		->apiCall($action = 'add');
} catch (Exception $e) {
	echo $e->getMessage();
}
print_r( $result );
